import type {
  Booking,
  Category,
  FaqItem,
  Helper,
  PlatformUser,
  Review,
  Testimonial,
} from '@/types'

export const CITIES = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Miami',
  'Seattle',
  'Boston',
  'Austin',
]

export const SERVICES = [
  { value: 'maid', label: 'Maid / Housekeeping' },
  { value: 'nanny', label: 'Nanny' },
  { value: 'babysitter', label: 'Babysitter' },
  { value: 'cook', label: 'Home Cook' },
  { value: 'elder-care', label: 'Elder Care' },
] as const

export const categories: Category[] = [
  {
    id: 'maid',
    label: 'Maids & Housekeeping',
    description: 'Cleaning, laundry, and everyday home upkeep.',
    icon: 'sparkles',
    helperCount: 320,
  },
  {
    id: 'nanny',
    label: 'Nannies',
    description: 'Full-time, dedicated childcare professionals.',
    icon: 'baby',
    helperCount: 210,
  },
  {
    id: 'babysitter',
    label: 'Babysitters',
    description: 'Reliable sitters for date nights and short care.',
    icon: 'heart-handshake',
    helperCount: 185,
  },
  {
    id: 'cook',
    label: 'Home Cooks',
    description: 'Fresh, home-style meals prepared for your family.',
    icon: 'chef-hat',
    helperCount: 140,
  },
  {
    id: 'elder-care',
    label: 'Elder Care',
    description: 'Compassionate assistance for aging loved ones.',
    icon: 'hand-heart',
    helperCount: 95,
  },
]

export const helpers: Helper[] = [
  {
    id: 'aisha-khan',
    name: 'Aisha Khan',
    avatar: '/helpers/aisha.png',
    service: 'nanny',
    serviceLabel: 'Nanny',
    bio: 'Certified childcare professional with a warm, patient approach. I help children thrive with structured routines, creative play, and lots of care.',
    city: 'New York',
    experienceYears: 8,
    rating: 4.9,
    reviewCount: 128,
    pricing: { hourly: 28, monthly: 3200, yearly: 34000 },
    skills: ['Newborn care', 'Meal prep', 'Homework help', 'First aid'],
    languages: ['English', 'Urdu', 'Hindi'],
    availability: 'Mon–Fri, 7am–7pm',
    verification: 'verified',
    completedJobs: 340,
    responseTime: 'Under 1 hour',
    gender: 'female',
  },
  {
    id: 'maria-santos',
    name: 'Maria Santos',
    avatar: '/helpers/maria.png',
    service: 'maid',
    serviceLabel: 'Maid / Housekeeping',
    bio: 'Detail-oriented housekeeper who treats every home like my own. Deep cleaning, organization, and laundry are my specialties.',
    city: 'Miami',
    experienceYears: 12,
    rating: 4.8,
    reviewCount: 203,
    pricing: { hourly: 24, monthly: 2600, yearly: 27500 },
    skills: ['Deep cleaning', 'Laundry & ironing', 'Organization', 'Pet friendly'],
    languages: ['English', 'Spanish', 'Portuguese'],
    availability: 'Mon–Sat, flexible',
    verification: 'verified',
    completedJobs: 512,
    responseTime: 'Under 2 hours',
    gender: 'female',
  },
  {
    id: 'priya-sharma',
    name: 'Priya Sharma',
    avatar: '/helpers/priya.png',
    service: 'babysitter',
    serviceLabel: 'Babysitter',
    bio: 'Energetic, reliable babysitter who kids adore. Great for evenings, weekends, and last-minute care with fun, safe activities.',
    city: 'Chicago',
    experienceYears: 4,
    rating: 4.7,
    reviewCount: 76,
    pricing: { hourly: 22, monthly: 2200, yearly: 23000 },
    skills: ['Evening care', 'Arts & crafts', 'Homework help', 'CPR certified'],
    languages: ['English', 'Hindi'],
    availability: 'Evenings & weekends',
    verification: 'verified',
    completedJobs: 198,
    responseTime: 'Under 30 minutes',
    gender: 'female',
  },
  {
    id: 'grace-okoro',
    name: 'Grace Okoro',
    avatar: '/helpers/grace.png',
    service: 'elder-care',
    serviceLabel: 'Elder Care',
    bio: 'Trained caregiver focused on dignity and companionship for seniors. Medication reminders, mobility support, and warm company.',
    city: 'Houston',
    experienceYears: 10,
    rating: 5.0,
    reviewCount: 91,
    pricing: { hourly: 30, monthly: 3400, yearly: 36000 },
    skills: ['Mobility support', 'Medication reminders', 'Companionship', 'First aid'],
    languages: ['English', 'French'],
    availability: 'Mon–Sun, day shifts',
    verification: 'verified',
    completedJobs: 265,
    responseTime: 'Under 1 hour',
    gender: 'female',
  },
  {
    id: 'linda-chen',
    name: 'Linda Chen',
    avatar: '/helpers/linda.png',
    service: 'cook',
    serviceLabel: 'Home Cook',
    bio: 'Home cook specializing in healthy, family-friendly meals across cuisines. I plan menus, shop, and cook fresh daily.',
    city: 'Seattle',
    experienceYears: 6,
    rating: 4.8,
    reviewCount: 64,
    pricing: { hourly: 26, monthly: 2800, yearly: 29500 },
    skills: ['Meal planning', 'Asian & Western cuisine', 'Grocery shopping', 'Diet-friendly'],
    languages: ['English', 'Mandarin'],
    availability: 'Mon–Fri, meal times',
    verification: 'pending',
    completedJobs: 142,
    responseTime: 'Under 2 hours',
    gender: 'female',
  },
  {
    id: 'james-miller',
    name: 'James Miller',
    avatar: '/helpers/james.png',
    service: 'maid',
    serviceLabel: 'Maid / Housekeeping',
    bio: 'Dependable housekeeper for busy households. Efficient, thorough, and respectful of your space and schedule.',
    city: 'Boston',
    experienceYears: 5,
    rating: 4.6,
    reviewCount: 48,
    pricing: { hourly: 23, monthly: 2400, yearly: 25000 },
    skills: ['General cleaning', 'Window care', 'Kitchen deep clean', 'Eco products'],
    languages: ['English'],
    availability: 'Tue–Sat, mornings',
    verification: 'verified',
    completedJobs: 120,
    responseTime: 'Under 3 hours',
    gender: 'male',
  },
]

export const reviews: Review[] = [
  {
    id: 'r1',
    author: 'Sophia Bennett',
    avatar: '',
    rating: 5,
    date: '2 weeks ago',
    comment:
      'Aisha has been amazing with our two kids. Punctual, caring, and genuinely invested in their well-being. Highly recommend!',
    helperId: 'aisha-khan',
    helperName: 'Aisha Khan',
  },
  {
    id: 'r2',
    author: 'Daniel Reyes',
    avatar: '',
    rating: 5,
    date: '1 month ago',
    comment:
      'Maria transformed our home. Everything is spotless and organized. She is trustworthy and professional.',
    helperId: 'maria-santos',
    helperName: 'Maria Santos',
  },
  {
    id: 'r3',
    author: 'Emily Carter',
    avatar: '',
    rating: 4,
    date: '3 weeks ago',
    comment:
      'Priya is wonderful with our toddler. Very reliable for weekend evenings. Kids always look forward to seeing her.',
    helperId: 'priya-sharma',
    helperName: 'Priya Sharma',
  },
  {
    id: 'r4',
    author: 'Michael Nguyen',
    avatar: '',
    rating: 5,
    date: '5 days ago',
    comment:
      'Grace cares for my mother with so much patience and warmth. We finally have peace of mind. Thank you Helper4U.',
    helperId: 'grace-okoro',
    helperName: 'Grace Okoro',
  },
  {
    id: 'r5',
    author: 'Olivia Martins',
    avatar: '',
    rating: 5,
    date: '1 week ago',
    comment:
      'Linda cooks the most delicious, healthy meals. Our whole family eats better now. Worth every penny.',
    helperId: 'linda-chen',
    helperName: 'Linda Chen',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sophia Bennett',
    role: 'Mother of two, New York',
    avatar: '',
    rating: 5,
    quote:
      'Finding a trustworthy nanny used to be stressful. Helper4U verified everything for me — I booked Aisha in minutes and never looked back.',
  },
  {
    id: 't2',
    name: 'Daniel Reyes',
    role: 'Homeowner, Miami',
    avatar: '',
    rating: 5,
    quote:
      'The verification badges gave me real confidence. My housekeeper is fantastic and the flexible monthly plan fits our budget perfectly.',
  },
  {
    id: 't3',
    name: 'Michael Nguyen',
    role: 'Son & caregiver, Houston',
    avatar: '',
    rating: 5,
    quote:
      'Elder care is deeply personal. Helper4U matched us with Grace, who treats my mother like family. I cannot recommend it enough.',
  },
]

export const faqs: FaqItem[] = [
  {
    question: 'How are helpers verified on Helper4U?',
    answer:
      'Every helper completes identity verification, background checks, and reference validation before appearing on the platform. Verified helpers display a badge on their profile.',
  },
  {
    question: 'What service plans are available?',
    answer:
      'You can book helpers on an hourly basis for one-off needs, or choose monthly and yearly plans for ongoing support at a discounted rate.',
  },
  {
    question: 'Can I cancel or reschedule a booking?',
    answer:
      'Yes. You can reschedule or cancel from your dashboard up to 24 hours before the scheduled time at no charge. Late cancellations may incur a small fee.',
  },
  {
    question: 'How do payments work?',
    answer:
      'Payments are handled securely through the platform. You are only charged once a booking is confirmed, and funds are released to helpers after the service is completed.',
  },
  {
    question: 'What if I am not satisfied with a helper?',
    answer:
      'Your satisfaction matters. If a service does not meet expectations, contact our support team within 48 hours and we will help resolve it or find a replacement.',
  },
]

export const bookings: Booking[] = [
  {
    id: 'BK-1042',
    helperId: 'aisha-khan',
    helperName: 'Aisha Khan',
    helperAvatar: '/helpers/aisha.png',
    service: 'Nanny',
    plan: 'monthly',
    date: '2026-07-20',
    time: '08:00 AM',
    duration: 'Full month',
    address: '221B Parkside Ave, New York',
    amount: 3200,
    status: 'confirmed',
    customerName: 'Sophia Bennett',
  },
  {
    id: 'BK-1039',
    helperId: 'maria-santos',
    helperName: 'Maria Santos',
    helperAvatar: '/helpers/maria.png',
    service: 'Housekeeping',
    plan: 'hourly',
    date: '2026-07-18',
    time: '10:00 AM',
    duration: '4 hours',
    address: '88 Ocean Dr, Miami',
    amount: 96,
    status: 'in-progress',
    customerName: 'Daniel Reyes',
  },
  {
    id: 'BK-1031',
    helperId: 'priya-sharma',
    helperName: 'Priya Sharma',
    helperAvatar: '/helpers/priya.png',
    service: 'Babysitting',
    plan: 'hourly',
    date: '2026-07-10',
    time: '06:00 PM',
    duration: '5 hours',
    address: '14 Lakeview Rd, Chicago',
    amount: 110,
    status: 'completed',
    customerName: 'Emily Carter',
  },
  {
    id: 'BK-1028',
    helperId: 'grace-okoro',
    helperName: 'Grace Okoro',
    helperAvatar: '/helpers/grace.png',
    service: 'Elder Care',
    plan: 'monthly',
    date: '2026-07-01',
    time: '09:00 AM',
    duration: 'Full month',
    address: '9 Rosewood St, Houston',
    amount: 3400,
    status: 'completed',
    customerName: 'Michael Nguyen',
  },
  {
    id: 'BK-1024',
    helperId: 'linda-chen',
    helperName: 'Linda Chen',
    helperAvatar: '/helpers/linda.png',
    service: 'Home Cooking',
    plan: 'hourly',
    date: '2026-06-28',
    time: '05:00 PM',
    duration: '3 hours',
    address: '30 Pine St, Seattle',
    amount: 78,
    status: 'cancelled',
    customerName: 'Olivia Martins',
  },
]

export const platformUsers: PlatformUser[] = [
  {
    id: 'U-201',
    name: 'Sophia Bennett',
    email: 'sophia.b@example.com',
    role: 'user',
    city: 'New York',
    joined: '2025-11-02',
    bookings: 12,
    status: 'active',
    avatar: '',
  },
  {
    id: 'U-202',
    name: 'Daniel Reyes',
    email: 'daniel.r@example.com',
    role: 'user',
    city: 'Miami',
    joined: '2025-12-14',
    bookings: 7,
    status: 'active',
    avatar: '',
  },
  {
    id: 'U-203',
    name: 'Emily Carter',
    email: 'emily.c@example.com',
    role: 'user',
    city: 'Chicago',
    joined: '2026-01-08',
    bookings: 3,
    status: 'active',
    avatar: '',
  },
  {
    id: 'U-204',
    name: 'Olivia Martins',
    email: 'olivia.m@example.com',
    role: 'user',
    city: 'Seattle',
    joined: '2026-02-19',
    bookings: 5,
    status: 'suspended',
    avatar: '',
  },
]

export function getHelperById(id: string): Helper | undefined {
  return helpers.find((h) => h.id === id)
}

export function getReviewsForHelper(id: string): Review[] {
  return reviews.filter((r) => r.helperId === id)
}
